sudo: required
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build master branch only
before_install:
    - npm install -g hexo-cli    
install:
    - npm install
    - npm install hexo-deployer-git --save    
script:
  - hexo clean
  - hexo generate # generate static files
after_script:
    - git config user.name "Bryan_Kan"
    - git config user.email "kantongyi1997@outlook.com"
    - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
    - hexo deploy
 